#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define NO_USB_STARTUP_CHECK

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#define MK_KINETIC_SPEED

#define MOUSEKEY_MOVE_DELTA 2
#define MOUSEKEY_INITIAL_SPEED 20
#define MOUSEKEY_DECELERATED_SPEED 40
#define MOUSEKEY_BASE_SPEED 200
#define MOUSEKEY_ACCELERATED_SPEED 500